// Generated by scripts/generate-schemas.ts
// Do not edit this file directly

export interface BoxScores {
  game_id: string;
  team_abbreviation: string;
  entity_id: string;
  player_name: string;
  minutes: string;
  points: number;
  rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fg_made: number;
  fg_attempted: number;
  fg3_made: number;
  fg3_attempted: number;
  ft_made: number;
  ft_attempted: number;
  starter: number;
  period: string;
}

export interface Schedule {
  game_id: string;
  game_date: Date;
  home_team_id: number;
  away_team_id: number;
  home_team_abbreviation: string;
  away_team_abbreviation: string;
  home_team_score: number;
  away_team_score: number;
  game_status: string;
  season_year?: number;
  season_type?: string;
  created_at: Date;
}

export interface TeamStats {
  game_id: string;
  team_abbreviation: string;
  period: string;
  minutes: string;
  points: number;
  rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fg_made: number;
  fg_attempted: number;
  fg3_made: number;
  fg3_attempted: number;
  ft_made: number;
  ft_attempted: number;
}


export interface Player {
  playerId: string;
  playerName: string;
  minutes: string;
  points: number;
  rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fieldGoalsMade: number;
  fieldGoalsAttempted: number;
  threePointersMade: number;
  threePointersAttempted: number;
  freeThrowsMade: number;
  freeThrowsAttempted: number;
  plusMinus: number;
  starter: boolean;
  oncourt?: boolean;
  played?: boolean;
}

export interface Team {
  teamId: string;
  teamName: string;
  teamAbbreviation: string;
  score: number;
  players: Player[];
}
