// Generated by scripts/generate-schemas.ts
// Do not edit this file directly

export interface BoxScores {
  game_id: string;
  team_id: string;
  entity_id: string;
  player_name: string;
  minutes: string;
  points: number;
  rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fg_made: number;
  fg_attempted: number;
  fg3_made: number;
  fg3_attempted: number;
  ft_made: number;
  ft_attempted: number;
  plus_minus: number;
  starter: number;
  period: string;
}

export interface Schedule {
  game_id: string;
  game_date: Date;
  home_team_abbreviation: string;
  away_team_abbreviation: string;
  home_team_score: number;
  away_team_score: number;
  status: string;
  created_at: Date;
}

export interface TeamStats {
  game_id: string;
  team_id: string;
  period: string;
  minutes: string;
  points: number;
  rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fg_made: number;
  fg_attempted: number;
  fg3_made: number;
  fg3_attempted: number;
  ft_made: number;
  ft_attempted: number;
  offensive_possessions: number;
  defensive_possessions: number;
}
